<?php
/**
* Class for the Redux importer.
*
* @see http://codestarframework.com/
*
* @package Merlin WP
*/

class Merlin_Codestar_Importer {
	/**
	* Import Redux data from a JSON file, generated by the Redux plugin.
	*
	* @param array $import_data Array of arrays. Child array contains 'option_name' and 'file_path'.
	*
	* @return boolean
	*/

	public static function import( $import_data ) {
		// Codestar plugin is not active!
		if ( ! class_exists( 'CSF' ) || empty( $import_data ) ) {
		    return false;
		}
		global $wp_filesystem;

		require_once ( ABSPATH . '/wp-admin/includes/file.php' );
		WP_Filesystem();

		//theme-options
		$theme_options = get_parent_theme_file_path( '/inc/merlin/demodata/theme-options.json' );
		$theme_options_raw_data =  $wp_filesystem->get_contents( $theme_options ) ;
		$theme_options_data = maybe_unserialize(json_decode( $theme_options_data, true ));
		update_option( 'crsine_theme_options', $theme_options_data);

		//
		$booking_opiton = get_parent_theme_file_path( '/inc/merlin/demodata/booking-options.json' );
	    $booking_options_raw_data =  $wp_filesystem->get_contents( $booking_opiton ) ;
	    $booking_options_data     = maybe_unserialize(json_decode( $booking_options_raw_data, true ));
	    update_option( 'crsine_car_wash_booking_options', $booking_options_data);
		return true;
	}
}